<!DOCTYPE html>
<head>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            padding: 15px;
        }
    </style>
    <title>Delete product</title>
</head>
<form action="/product/<?= $product['id'] ?>" method="post">
    <input type="hidden" name="_METHOD" value="DELETE">
    <div>
        <label>
            <b>Are you sure that you want to delete this product?</b>
            <br>
            <br>
            <table style="width:100%">
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                </tr>
                <tr>
                    <td><?= $product['id'] ?></td>
                    <td><?= $product['title'] ?></td>
                </tr>
            </table>
        </label>
    </div>
    <br>
    <input type="hidden" name="product[id]" value="<?= $product['id'] ?>">
    <input type="submit"  value="Yes! Delete it!">
</form>
<br>
<form action="/product/<?= $product['id'] ?>" method="get">
    <input type="submit" value="No! Go Back!" />
</form>