<!DOCTYPE html>
<html>
<head>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            padding: 15px;
        }
    </style>
</head>
<body>
<a href="/">Main page</a>
<br>
<a href="/products">All products</a>
<br>
<a href="/products/new">Add new product</a>
<br>
<br>
<div>Search by Title:<br></div>
<form action="/products" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($searchRequest) ?>" />
    <input type="submit" value="Search" />
</form>
<br>
<table style="width:100%">
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
    </tr>
    <?php foreach ($products as $product): ?>
        <tr>
            <td><a href="/product/<?= $product['id'] ?>"><?= $product['id'] ?> </a> </td>
            <td><?= $product['title'] ?></td>
            <td><?= $product['description'] ?></td>
        </tr>
    <?php endforeach ?>
</table>
<br>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Back</a> / <a href="?page=<?= $page + 1 ?>">Forwad</a>
</body>
</html>