<!-- templates/users/new.phtml -->
<a href="/products">Show all products</a>
<br>
<br>
<form action="/products" method="post">
    <div>Title:<span style='color: red;'> *</span><br>
            <input type="text" name="product[title]" value="<?= htmlspecialchars($product['title']) ?>">
        <?php if (isset($errors['title'])): ?>
            <div><b><?= $errors['title'] ?></b></div>
        <?php endif ?>
    </div>
    <div>Description:<span style='color: #ff0000;'> *</span><br>
            <input type="text" name="product[description]" value="<?= htmlspecialchars($product['description']) ?>">
        <?php if (isset($errors['description'])): ?>
            <div><b><?= $errors['description'] ?></b></div>
        <?php endif ?>
    </div>
    <br>
    <input type="submit" value="Add new product">
    <br>
</form>
