<!DOCTYPE html>
<html>
<head>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            padding: 15px;
        }
    </style>
</head>
<body>
<a href="/products/new">Add new product</a>
<br>
<a href="/">Main page</a>
<br>
<a href="/products">All products</a>
<br>
<br>
<div>Product:<br></div>

<table style="width:100%">
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
    </tr>
        <tr>
            <td><?= $product['id'] ?></td>
            <td><?= $product['title'] ?></td>
            <td><?= $product['description'] ?></td>
        </tr>

</table>
</body>
</html>