<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<!-- BEGIN (write your solution here) -->
<?php if (is_null($currentUser)): ?>
    <forh action="/session" method="post">
        <h1>Sign In</h1>
        <div>Login:<span style='color: red;'> *</span><br>
            <label>
                <input type="text" name="user[name]" value="">
            </label>
        </div>
        <div>Password:<span style='color: #ff0000;'> *</span><br>
            <label>
                <input type="password" name="user[password]" value="">
            </label>
        </div>
        <br>
        <input type="submit" value="Sign In">
        <h5><i>Login - Admin, pass - secret</i></h5>
    </forh>
<?php endif ?>

<?php if (!is_null($currentUser)): ?>
    <h1>Welcome, <?= $currentUser['name'] ?>!</h1>
    <a href="/">Main page</a>
    <br>
    <a href="/products">All products</a>
    <br>
    <a href="/products/new">Add new product</a>
    <br>
    <br>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Logout">
    </form>
<?php endif ?>
